# Generated by Django 4.2.1 on 2023-05-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('phone_number', models.CharField(blank=True)),
                ('email', models.CharField(blank=True)),
                ('origin', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('total_unit', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HouseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.IntegerField(blank=True)),
                ('bathroom', models.IntegerField(default=1)),
                ('bedroom', models.IntegerField(default=1)),
                ('necessity', models.JSONField(blank=True)),
                ('homestay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.homestay')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('total_adult', models.IntegerField(blank=True)),
                ('total_child', models.IntegerField(blank=True, default=0)),
                ('purpose_of_booking', models.CharField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customer')),
            ],
        ),
    ]
