# Generated by Django 4.2.1 on 2023-05-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_booking_house_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseunit',
            name='necessity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
