# Generated by Django 4.2.1 on 2023-05-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_houseunit_necessity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseunit',
            old_name='homestay_id',
            new_name='homestay',
        ),
    ]
