# Generated by Django 4.2.1 on 2023-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_homestay_id_houseunit_homestay'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseunit',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
