# Generated by Django 4.2.1 on 2023-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_houseunit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
