# Generated by Django 4.2.1 on 2023-06-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_booking_invoice_content_booking_invoice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invoice_content',
            field=models.BinaryField(null=True),
        ),
    ]
