# Generated by Django 4.2.1 on 2023-06-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_booking_invoice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invoice_content',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_child',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
