# Generated by Django 4.2.1 on 2023-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_booking_invoice_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='purpose_of_booking',
            field=models.CharField(blank=True, null=True),
        ),
    ]
