# Generated by Django 4.2.1 on 2023-06-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_booking_purpose_of_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.BinaryField(default=None)),
                ('receipt_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='invoice_content',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='invoice_title',
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmation_code',
            field=models.UUIDField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='house_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.houseunit'),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.invoice'),
            preserve_default=False,
        ),
    ]
