# Generated by Django 4.2.1 on 2023-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_invoice_remove_booking_invoice_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirmation_code',
            field=models.CharField(unique=True),
        ),
    ]
