# Generated by Django 4.2.1 on 2023-06-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_booking_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(default='15:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(),
        ),
    ]
